Implement Set and Dict operations/operators
avrae/draconic pull request #6
Opened 2020-10-23 04:35 UTC by Infinidoge

### Summary
Implements the operators and operations for sets and dicts, adding relevant limits

Resolves #2 
Resolves #3 

Requires #5 for relevant ast operators

### Checklist

#### PR Type

- [x] This PR is a code change that implements a feature request.
- [ ] This PR fixes an issue.
- [ ] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
#### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes.

2020-10-23 04:36 UTC, Infinidoge commented
Some changes will need to be made to update this repo and avrae/avrae to use Python 3.9 (required for dictionary merge operator)

2020-11-24 20:20 UTC, mommothazaz123 requested changes

2020-11-24 20:20 UTC, mommothazaz123 commented on draconic/helpers.py
> +            return SafeSet(super().union(*s))
this should probably be `super.intersection`

2020-11-24 20:20 UTC, mommothazaz123 commented on draconic/helpers.py
> +            return SafeSet(super().union(*s))
this should probably be `super.symmetric_difference`

2020-11-24 20:20 UTC, mommothazaz123 commented on draconic/helpers.py
> +            return SafeSet(super().union(*s))
also, intersection's size check shouldn't be the sum, as the size of the intersection of two sets is guaranteed to be equal to or less than the size of the smaller set. It should check each set individually to make sure each set individually is not too large.

2020-11-25 17:29 UTC, mommothazaz123 requested changes

2020-11-25 17:29 UTC, mommothazaz123 commented on draconic/helpers.py
> +            self.update(self.intersection(*s))
This is not the same operation: 
```py
>>> a = {1, 2, 3}
>>> a.intersection_update({2, 3, 4})
>>> a
{2, 3}

>>> a = {1, 2, 3}
>>> a.update(a.intersection({2, 3, 4}))
>>> a
{1, 2, 3}
```

2020-11-25 17:29 UTC, mommothazaz123 commented on draconic/helpers.py
> +            self.update(self.difference(*s))
This is not the same operation:
```py
>>> a = {1, 2, 3}
>>> a.difference_update({2, 3, 4})
>>> a
{1}

>>> a = {1, 2, 3}
>>> a.update(a.difference({2, 3, 4}))
>>> a
{1, 2, 3}
```

2020-11-25 17:32 UTC, mommothazaz123 commented on draconic/helpers.py
> +            self.update(self.symmetric_difference(s))
This is not the same operation:
```py
>>> a = {1, 2, 3}
>>> a.symmetric_difference_update({2, 3, 4})
>>> a
{1, 4}

>>> a = {1, 2, 3}
>>> a.update(a.symmetric_difference({2, 3, 4}))
>>> a
{1, 2, 3, 4}
```

(it deleted my original comment for some reason)

2020-11-30 18:44 UTC, mommothazaz123 approved these changes
Get that green check on test coverage and LGTM 👍

2022-02-28 19:53 UTC, zhudotexe commented
Implemented in d7c2eacad011d87473a8944671c987bcb70b0d68; closing this PR as the upstream branch was deleted which made the merge conflict annoying to resolve

2022-02-28 19:53 UTC, closed without merging